---
# Source: machix/templates/machix-server/server-deployment.yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: istio-playground-v1
spec:
  replicas: 1
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 0
  template:
    metadata:
      labels:
        version: v1
        app: istio-playground
        component: api-server
    spec:
      containers:
      - name: istio-playground
        command: ["/usr/local/bin/entrypoint"]
        image: chechiachang/istio-playground:master-4455d44
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 10m
            memory: 25Mi
        env:
        - name: MESSAGE
          value: "v1"
