---
# Source: machix/templates/machix-server/server-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: &app-name machix-server
  labels:
    version: v1
    app: istio-playground
    component: api-server
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
  selector:
    version: v1
    app: istio-playground
    component: api-server
